{{- range .Values.versions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-{{ .name }}
  labels:
    app: {{ $.Values.app.name }}
    version: {{ .name }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.app.name }}
      version: {{ .name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.app.name }}
        version: {{ .name }}
        release: {{ $.Release.Name }}
    spec:
      containers:
        - name: name
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: routerule-{{ .name }}
  labels:
    app: {{ $.Values.app.name }}
    release: {{ $.Release.Name }}
spec:
  hosts:
    - {{ $.Values.gatewayHost }}  # Replace this with your gateway host
  http:
    - match:
        - headers:
            version:
              exact: {{ .name }}
      route:
        - destination:
            host: {{ $.Values.app.name }}-clusterIP
            subset: {{ .name }}
{{ end }}
